// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block       = require("bs-platform/lib/js/block.js");
var Curry       = require("bs-platform/lib/js/curry.js");
var React       = require("react");
var Pervasives  = require("bs-platform/lib/js/pervasives.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Stepper");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return React.createElement("div", undefined, React.createElement("button", {
                      onClick: Curry._1(self[/* reduce */1], (function () {
                              return /* Decrease */1;
                            }))
                    }, " - "), React.createElement("div", undefined, Pervasives.string_of_int(self[/* state */2][/* value */0])), React.createElement("button", {
                      onClick: Curry._1(self[/* reduce */1], (function () {
                              return /* Increase */0;
                            }))
                    }, " + "));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* value */0];
    });
  newrecord[/* reducer */12] = (function (action, state) {
      if (action !== 0) {
        return /* Update */Block.__(0, [/* record */[/* value */state[/* value */0] - 1 | 0]]);
      } else {
        return /* Update */Block.__(0, [/* record */[/* value */state[/* value */0] + 1 | 0]]);
      }
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
